[package]
name = "nimbledroidrs"
version = "0.0.1"
authors = ["Will Hawkins <whh8b@obs.cr>"]
edition = "2018"

[[bin]]
name = "nimbledroidrs-test"
path = "src/main.rs"

[dependencies]
reqwest = "0.9.22"
base64 = "0.11.0"
serde_json = "1.0.41"
